apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: swe645-hw4-cluster
spec:
  kafka:
    version: 2.7.0
    replicas: 3
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    resources:
      requests:
        memory: 100Mi
        cpu: "1"
      limits:
        memory: 100Mi
        cpu: "1"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: false
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration: 
          bootstrap:
            host: bootstrap.myingress.com
          brokers:
          - broker: 0
            host: broker-0.myingress.com
          - broker: 1
            host: broker-1.myingress.com
          - broker: 2
            host: broker-2.myingress.com
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
    storage:
        type: persistent-claim
        size: 100Mi
  zookeeper:
    replicas: 3
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      requests:
        memory: 100Mi
        cpu: "1"
      limits:
        memory: 100Mi
        cpu: "1"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 100Mi
  entityOperator:
    topicOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        requests:
          memory: 100Mi
          cpu: "1"
        limits:
          memory: 100Mi
          cpu: "1"
    userOperator: {}
