apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: swe645-topic
  labels:
    strimzi.io/cluster: swe645-hw4-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 

